UserAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 UOS'
定时:
  周几至周几: 1-7
  时: 8
  分: 0
通知:
  通知总开关: 开
  通知方式:
    server酱:
      通知开关: 开
      sendkey: '你的server酱sendkey'
    邮箱:
      通知开关: 开
      发送邮箱账号: '你的发送邮箱'
      发送邮箱授权码: '你的发送邮箱授权码'
      接收邮箱账号: '接收邮箱账号'
    企业微信: 
      通知开关: 开
      企业ID: '企业微信ID'
      应用ID: '企业微信应用ID'
      应用Secret: '企业微信应用ID'
      接收者用户名: '接受者用户名'
网站:
  hdzone:
    访问签到开关: 开
    账号: ''
    密码: ''
    cookies: '你的cookie'
  pthome:
    访问签到开关: 开
    账号: ''
    密码: ''
    cookies: ''你的cookie'
  hdarea:
    访问签到开关: 开
    账号: ''
    密码: ''
    cookies: ''你的cookie'
  hdatmos:
    访问签到开关: 开
    账号: ''
    密码: ''
    cookies: ''你的cookie'
  pttime:
    访问签到开关: 开
    账号: ''
    密码: ''
    cookies: ''你的cookie'
  m-team:
    访问签到开关: 开
    账号: ''
    密码: ''
    cookies: ''你的cookie'
